### PR TITLE
ci(workflows): added workflow for release management

### PR DESCRIPTION
**Pull request by H4ad**
I'm using https://github.com/google-github-actions/release-please-action, which is the same used by NPM team, is a very good release manager that enable us to control exactly what goes in the next release.

TODO:

- [ ] Create a token for Github Action 
- [ ] Create NPM Token

I don't have access to the settings of the repo, so @RafaelGSS can you help me with that?

### CODE REVIEW

**Comment by RafaelGSS** [comment]
The default settings for all my packages are: do not allow npm_token for automation - for security reasons. Let me see if I can change it for this specific repo.

**Comment by H4ad** [comment]
I think we can remove the part of NPM deployment and leave just the tag/changelog generation.

But if you can enable it just for this repo, it will be waaay easier to deploy new things.

The `GITHUB_TOKEN` didn't work well for this github action, so we need to create a new token manually.

**Comment by RafaelGSS** [comment]
> The GITHUB_TOKEN didn't work well for this github action, so we need to create a new token manually.

Which permission should it have?

**Comment by H4ad** [comment]
I don't have idea, in the documentation they didn't specify.

But I'm trying to add support for this release please on my repo and I added
- issues
- code
- pr
- actions

All of them are also write, because this lib can trigger a workflow.

**Comment by H4ad** [comment]
Example of how the PR will be: https://github.com/H4ad/serverless-adapter/pull/153

**Pull request closed without merging**
